### ISSUE TITLE
Help with installation.

### ISSUE THREAD

**Issue by deadmanbomber** [Rinnegatamante/Sunshell#6]
I am having some difficulties installing Sunshell on my New 3DSXL. I have downloaded the lastest version and followed the instructions. When I go to boot either the CIA or the 3DSX version, it just gives me a black screen. I tried multiple times to no avail. Do I need something else besides the files from Sunshell?

**Comment by Rinnegatamante** [comment]
Sunshell is discontinued and most likely unusable on current firmwares.
